Web_QLDiemSV/Models/BangDiem.cs
namespace Web_QLDiemSV.Models
{
    public class BangDiem
    {
        public int MaBangDiem { get; set; }
        public int MaMonHoc { get; set; }
        public string? TenMonHoc { get; set; }
        public int SoTinChi { get; set; }
        public double ChuyenCan { get; set; }
        public double BaiTap { get; set; }
        public double KiemTra { get; set; }
        public double ThucHanh { get; set; }
        public double Thi { get; set; }
        public double TongKet { get; set; }
        public int Nam { get; set; }
        public int Ky { get; set; }
    }
}

Web_QLDiemSV/Models/ErrorViewModel.cs
namespace Web_QLDiemSV.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web_QLDiemSV/Models/SinhVien.cs
namespace Web_QLDiemSV.Models
{
    public class SinhVien
    {
        public int MaSv { get; set; }
        public string Ho { get; set; } = null!;
        public string Ten { get; set; } = null!;
        public string DiaChi { get; set; } = null!;
        public string Sdt { get; set; } = null!;
    }
}

Web_QLDiemSV/Models/TaiKhoan.cs
namespace Web_QLDiemSV.Models
{
    public class TaiKhoan
    {
        public TaiKhoan()
        {
 
        }
        public TaiKhoan(int maSinhVien, string matKhau)
        {
            MaSinhVien = maSinhVien;
            MatKhau = matKhau;
        }

        public int MaSinhVien { get; set; }
        public string MatKhau { get; set; }
    }
}

Web_QLDiemSV/Controllers/BangDiemController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Web_QLDiemSV.Models;
using Web_QLDiemSV.Repository;

namespace Web_QLDiemSV.Controllers
{
    public class BangDiemController : Controller
    {
        private readonly ISinhVienRepo _repo;
        private const string SessionMaSv = "maSv";

        public BangDiemController(ISinhVienRepo repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            var maSv = HttpContext.Session.GetString(SessionMaSv);
            if (maSv == null || maSv == "")
            {
                return RedirectToAction(actionName: "Index", controllerName: "Home");
            }

            List<BangDiem> bd = _repo.GetBangDiem(Int32.Parse(maSv));
            var diemTheoKyNamHoc = bd.GroupBy(d => new { d.Nam, d.Ky })
                                            .Select(group => new { Nam = group.Key.Nam, Ky = group.Key.Ky, bd = group.ToList() })
                                            .ToList();
            return View(diemTheoKyNamHoc);
        }
    }
}

Web_QLDiemSV/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using Web_QLDiemSV.Models;
using Newtonsoft.Json;
using Web_QLDiemSV.Repository;


namespace Web_QLDiemSV.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ISinhVienRepo _repo;
        private const string SessionMaSv = "maSv";
        private const string login = "isLogin";

        public HomeController(ILogger<HomeController> logger, ISinhVienRepo repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(TaiKhoan objUser)
        {
            bool isLogin = _repo.PostDangNhap(objUser) == "true";
            if(isLogin)
            {
                HttpContext.Session.SetString(SessionMaSv, objUser.MaSinhVien.ToString());
                HttpContext.Session.SetString(login, "true");
                return RedirectToAction(actionName: "Index", controllerName: "SinhVien");
            }
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.SetString(SessionMaSv, "");
            HttpContext.Session.SetString(login, "false");
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web_QLDiemSV/Controllers/MatKhauController.cs
using Microsoft.AspNetCore.Mvc;
using Web_QLDiemSV.Models;
using Web_QLDiemSV.Repository;

namespace Web_QLDiemSV.Controllers
{
    public class MatKhauController : Controller
    {
        private readonly ISinhVienRepo _repo;
        private const string SessionMaSv = "maSv";
        private const string login = "isLogin";

        public MatKhauController(ISinhVienRepo repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            var maSv = HttpContext.Session.GetString(SessionMaSv);
            if (maSv == null || maSv == "")
            {
                return RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            return View();
        }

        [HttpPost]
        public IActionResult DoiMatKhau(TaiKhoan objUser)
        {
            objUser.MaSinhVien = Int32.Parse(HttpContext.Session.GetString(SessionMaSv));
            bool success = (int)_repo.PutMatKhau(objUser) == 200;
            if (success)
            {
                return RedirectToAction(actionName: "Index", controllerName: "SinhVien");
            }
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }
    }
}

Web_QLDiemSV/Controllers/SinhVienController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Web_QLDiemSV.Models;
using Web_QLDiemSV.Repository;

namespace Web_QLDiemSV.Controllers
{
    public class SinhVienController : Controller
    {
        private readonly ISinhVienRepo _repo;
        private const string SessionMaSv = "maSv";

        public SinhVienController(ISinhVienRepo repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            var maSv = HttpContext.Session.GetString(SessionMaSv);
            if (maSv == null || maSv == "")
            {
                return RedirectToAction(actionName: "Index", controllerName: "Home");
            }

            SinhVien sv = _repo.GetSinhVien(Int32.Parse(maSv));
            return View(sv);
        }
    }
}

Web_QLDiemSV/Views/BangDiem/Index.cshtml
@model IEnumerable<dynamic>

@{
    ViewData["Title"] = "Trang bảng điểm";
}

<h1>Bảng điểm sinh viên</h1>
<hr/>
@foreach (var kyNamHoc in Model)
{
    <h4>Năm học @kyNamHoc.Nam - Học kỳ @kyNamHoc.Ky</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Mã môn học</th>
                <th>Tên môn học</th>
                <th>Số Tín chỉ</th>
                <th>Chuyên cần</th>
                <th>Bài tập</th>
                <th>Kiểm tra</th>
                <th>Thực hành</th>
                <th>Thi</th>
                <th>Tổng kết</th>
            </tr>
        </thead> 
        <tbody>
            @{double tongDiem = 0;}
            @{double tongSoTc = 0;}
            @foreach (var bangDiem in kyNamHoc.bd)
            {
                <tr>
                    <td>@bangDiem.MaMonHoc</td>
                    <td>@bangDiem.TenMonHoc</td>
                    <td>@bangDiem.SoTinChi</td>
                    <td>@bangDiem.ChuyenCan</td>
                    <td>@bangDiem.BaiTap</td>
                    <td>@bangDiem.KiemTra</td>
                    <td>@bangDiem.ThucHanh</td>
                    <td>@bangDiem.Thi</td>
                    <td>@bangDiem.TongKet</td>
                </tr>
                tongDiem += @bangDiem.TongKet * @bangDiem.SoTinChi;
                tongSoTc += @bangDiem.SoTinChi;
            }
            @{double diemtb = Math.Round(tongDiem / tongSoTc, 2);}
        </tbody> 
    </table>
    <label> - Điểm trung bình học kỳ hệ 10: @diemtb </label>
    <hr/>
}

Web_QLDiemSV/Views/Home/Index.cshtml
@model Web_QLDiemSV.Models.TaiKhoan

@{
    ViewData["Title"] = "Trang đăng nhập";
}

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                @using (Html.BeginForm("Login", "Home", FormMethod.Post))
                {
                    <div class="form-group">
                        <label>Mã sinh viên</label>
                    </div>
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        
                        @Html.TextBoxFor(m => m.MaSinhVien, "", new { @class = "form-control", @placeholder = "Mã sinh viên" })

                    </div>
                    <br />
                    <div class="form-group">
                        <label>Mật khẩu</label>
                    </div>
                    <div class="form-group">
                        @Html.PasswordFor(m => m.MatKhau, new { @class = "form-control", @placeholder = "Mật khẩu" })
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Đăng nhập" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Web_QLDiemSV/Views/MatKhau/Index.cshtml
@model Web_QLDiemSV.Models.TaiKhoan

@{
    ViewData["Title"] = "Đổi mật khẩu";
}

<h1>Đổi mật khẩu</h1>

<hr />
<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                @using (Html.BeginForm("DoiMatKhau", "MatKhau", FormMethod.Post))
                {
                    <div class="form-group">
                        <label>Nhập mật khẩu mới</label>
                    </div>
                    <br/>
                    <div class="form-group">
                        @Html.PasswordFor(m => m.MatKhau, new { @class = "form-control", @placeholder = "Nhập mật khẩu" })
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Đổi mật khẩu" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Web_QLDiemSV/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_QLDiemSV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_QLDiemSV.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web_QLDiemSV</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (@Accessor.HttpContext.Session.GetString("isLogin") == null
                            || @Accessor.HttpContext.Session.GetString("isLogin") == "false")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Đăng nhập</a>
                            </li>
                        }
                        @if (@Accessor.HttpContext.Session.GetString("isLogin") == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SinhVien" asp-action="Index">Thông tin sinh viên</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BangDiem" asp-action="Index">Bảng điểm sinh viên</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MatKhau" asp-action="Index">Đổi mật khẩu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Đăng xuất</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web_QLDiemSV - <a asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web_QLDiemSV/Views/SinhVien/Index.cshtml
@model Web_QLDiemSV.Models.SinhVien

@{
    ViewData["Title"] = "Trang thông tin sinh viên";
}

<h1>Thông tin sinh viên</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Mã sinh viên
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaSv)
        </dd>
        <dt class = "col-sm-2">
            Họ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ho)
        </dd>
        <dt class = "col-sm-2">
            Tên
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            Địa chỉ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class = "col-sm-2">
            Số điện thoại
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sdt)
        </dd>
    </dl>
</div>